# WINDOW SETTINGS
WIDTH = 1024
HEIGHT = 768

# THICKNESS SETTINGS
P1_WIDTH = 20
P1_HEIGHT = 100
P2_WIDTH = 20
P2_HEIGHT = 100
BALL_WIDTH = 30
BALL_HEIGHT = BALL_WIDTH

# SPEED SETTINGS
P1_STEP_SIZE = P1_HEIGHT / 5
P2_STEP_SIZE = P2_HEIGHT / 5
BALL_SPEED = 5
BALL_ACC = 1.15
TICK_SPEED = 10

P1_NAME = 'Player 1'
P2_NAME = 'Player 2'
SLEEP_TIME = 0.5

# GAME FIELD SETTINGS
BORDER_SCALE = 60 # bigger -> thinner borders
BORDER_THICKNESS = int(WIDTH / BORDER_SCALE + HEIGHT / BORDER_SCALE)
P1_POSX = 0 + BORDER_THICKNESS
P1_POSY = int(HEIGHT / 2 - P1_HEIGHT / 2) 
P2_POSX = WIDTH - BORDER_THICKNESS - P2_WIDTH
P2_POSY = int(HEIGHT / 2 - P2_HEIGHT / 2)
BALL_POSX = WIDTH / 2 - BALL_WIDTH / 2
BALL_POSY = HEIGHT / 2

# SCORES SETTINGS
S1_FONT_SIZE = 25
S2_FONT_SIZE = 25
S1_POSX = WIDTH / 4
S1_POSY = HEIGHT / 4
S2_POSX = WIDTH * 3 / 4
S2_POSY = HEIGHT / 4
S1_WIDTH = BORDER_THICKNESS * 3
S1_HEIGHT = BORDER_THICKNESS * 3
S2_WIDTH = BORDER_THICKNESS * 3
S2_HEIGHT = BORDER_THICKNESS * 3
S1_FONT = 'Arial'
S2_FONT = 'Arial'

WIN_LABEL_BG_COLOR = 'darkgray'
WIN_LABEL_FONT_SIZE = 50
WIN_LABEL_POSX = WIDTH / 4
WIN_LABEL_POSY = HEIGHT / 4
WIN_LABEL_WIDTH = WIDTH / 2
WIN_LABEL_HEIGHT = HEIGHT / 2
WIN_LABEL_COLOR = 'magenta' 




# COLORS
P1_COLOR = 'red'
P2_COLOR = 'blue'
S1_COLOR = 'red'
S2_COLOR = 'blue'
BALL_COLOR = 'lightblue'
FIELD_COLOR = 'black'
BORDER_COLOR = 'gray'
