# WINDOW SETTINGS
WIDTH = 1024
HEIGHT = 768

# THICKNESS SETTINGS
P1_WIDTH = 20
P1_HEIGHT = 100
P2_WIDTH = 20
P2_HEIGHT = 100
BALL_WIDTH = 30
BALL_HEIGHT = BALL_WIDTH

# SPEED SETTINGS
P1_STEP_SIZE = P1_HEIGHT / 5
P2_STEP_SIZE = P2_HEIGHT / 5
BALL_SPEED = 5
BALL_ACC = 1.15
TICK_SPEED = 10


# GAME FIELD SETTINGS
BORDER_SCALE = 60 # bigger -> thinner borders
BORDER_THICKNESS = int(WIDTH / BORDER_SCALE + HEIGHT / BORDER_SCALE)
P1_POSX = 0 + BORDER_THICKNESS
P1_POSY = int(HEIGHT / 2 - P1_HEIGHT / 2) 
P2_POSX = WIDTH - BORDER_THICKNESS - P2_WIDTH
P2_POSY = int(HEIGHT / 2 - P2_HEIGHT / 2)
BALL_POSX = WIDTH / 2 - BALL_WIDTH / 2
BALL_POSY = HEIGHT / 2




# COLORS
P1_COLOR = 'red'
P2_COLOR = 'blue'
BALL_COLOR = 'lightblue'
FIELD_COLOR = 'black'
BORDER_COLOR = 'gray'
